### ISSUE TITLE
Exception occurs when leaving specific constants blank.

### ISSUE THREAD

**Issue by hellobaka** [Siujoeng-Lau/WorkersProxy#2]
**Describe the bug**
I set the 'const main_domain' equals "", since I don't want to bind WorkersProxy to my custom domain. However, after doing that, Cloudflare thorws an exception.

**To Reproduce**
Set the 'const main_domain' equals "", and then deploy the code.

**Comment by Siujoeng-Lau** [comment]
Thanks for your feedback.
Already fixed this bug in the most recent commit: 1a04bb6b7a96b6866dff02dbda7e4d8a60ee33fc
