### ISSUE TITLE
报错，怎么解决，请求帮助

### ISSUE THREAD

**Issue by ourlove5** [Siujoeng-Lau/WorkersProxy#4]
配置
const domain_list = ['google.ourlove5.com/', 'google.ourlove5.workers.dev/']
const upstream = 'https://www.google.com/'
const upstream_mobile = 'https://www.google.com/'
const blocked_region = ['KP', 'SY', 'PK', 'CU']
const blocked_ip_address = ['1.1.1.1','2.2.2.2']
访问 google.ourlove5.com/
报错
Error 1003 Ray ID: xxx
Direct IP access not allowed

**Comment by Siujoeng-Lau** [comment]
domain_list 的域名要加上 https://

**Comment by ourlove5** [comment]
> domain_list的域名要加上https：//

谢谢，原来是如此低级的错误

**Comment by Siujoeng-Lau** [comment]
> > domain_list的域名要加上https：//
> 
> 谢谢，原来是如此低级的错误

问题解决了嘛
