### ISSUE TITLE
subdomain error 522 or 1016

### ISSUE THREAD

**Issue by wawnnzxd** [Siujoeng-Lau/WorkersProxy#6]
Add a CNAME record of your domain which directs to the subdomain of your workers.
subdomain:
if I add:zouxiaodong.workers.dev to cname, when use search,it's show:
Error 1016 Origin DNS error

if I add:googlesearch.zouxiaodong.workers.dev to cname it's show:
Error 522 Connection timed out

my subdomain is:
zouxiaodong.workers.dev

my workers url is:
googlesearch.zouxiaodong.workers.dev

current custom domain to cname I setting:
crystalmam.com is an alias of googlesearch.zouxiaodong.workers.dev and has its traffic proxied through Cloudflare.

you can  try to click url:
https://www.crystalmam.com

**Comment by Siujoeng-Lau** [comment]
应该将 crystalmam.com 用 CNAME 指向 **zouxiaodong.workers.dev**
然后去 Cloudflare 控制台的 Workers 页面 设置一下 Route: 将 https://www.crystalmam.com/* 指向你的 Worker
顺便贴一下 index.js 完整的配置?

**Comment by wawnnzxd** [comment]
非常感谢您抽时间答复这个问题。
